---
title: "Linear model on top 20 featured selected variables by LASSO"
author: "INER"
date: "`r date()`"
output: html_document
---


## Loading data and feature selected variables


```{r dependencies, include=FALSE}
library(dplyr)
library(ggplot2)
```

```{r loading_data}
## load LASSO feature selected variables
coefs <- read.csv("../data/lasso_only_numeric.csv", 
                  stringsAsFactors = FALSE)
## drop intercept coeficient
coefs <- filter(coefs, coefficient != "(Intercept)")

top20vars <- coefs$coefficient[1:20]


## load cleaned data
vih_data <- read.csv("../data/cleandata.csv", stringsAsFactors = FALSE)

## selecting CD4 increase variable as output for lm
vih_data$"output" <- vih_data$Delta_CD4_year1

## processing data for lasso
input <- vih_data[, names(vih_data) %in% c(top20vars, "output")]
```


## Fitting the linear model

```{r model_fitting}
## perform linear model
lModel <- lm(output~., data = input)
preds <- predict(lModel, newdata = input)

summary(lModel)
```



